-- Run this in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  guest_name text not null,
  guest_email text not null,
  guest_phone text,
  room_number text not null,
  room_type text not null,
  check_in date not null,
  check_out date not null,
  nights integer not null,
  amount numeric(12,2) not null,
  payment_status text not null default 'pending',
  payment_method text not null default 'pay_at_hotel',
  payment_reference text,
  booking_status text not null default 'Confirmed',
  created_at timestamptz default now(),
  constraint bookings_dates_valid check (check_out > check_in)
);

alter table public.profiles enable row level security;
alter table public.bookings enable row level security;

drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update using (auth.uid() = id);

drop policy if exists "bookings own select" on public.bookings;
create policy "bookings own select" on public.bookings for select using (auth.uid() = user_id);
drop policy if exists "bookings own insert" on public.bookings;
create policy "bookings own insert" on public.bookings for insert with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name','')) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
