
"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";

type Status="Pending"|"Confirmed"|"Checked in"|"Checked out"|"Cancelled";
type Reservation={id:number;guest:string;email:string;phone:string;room:string;type:string;checkIn:string;checkOut:string;status:Status;amount:number;paid:number;method:string};
type RoomStatus="Clean"|"Dirty"|"Occupied"|"Reserved"|"Maintenance";
type Room={number:string;type:string;status:RoomStatus;guest:string;rate:number;image:string};

const roomImages=[
"https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=900&q=80"
];
const hotelImages=[
"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
"https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1000&q=80",
"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=80"
];

const seedRooms:Room[]=[
["101","Deluxe","Occupied","Açelya Işık",140],["102","Deluxe","Clean","",140],["103","Suite","Dirty","",210],["104","Standard","Clean","",100],
["201","Standard","Occupied","Sony Entertainment",100],["202","Deluxe","Clean","",140],["203","Suite","Maintenance","",210],["204","Deluxe","Occupied","Sony Entertainment",140],
["301","Standard","Clean","",100],["302","Standard","Dirty","",100],["303","Deluxe","Clean","",140],["304","Suite","Clean","",210],
["305","Deluxe","Reserved","Marry TicketCoWorker",140],["401","Standard","Clean","",100],["402","Deluxe","Occupied","Khaled Hussein",140],["403","Suite","Clean","",210]
].map((x,i)=>({number:x[0] as string,type:x[1] as string,status:x[2] as RoomStatus,guest:x[3] as string,rate:x[4] as number,image:roomImages[i%roomImages.length]}));

const seedReservations:Reservation[]=[
{ id:1001,guest:"Açelya Işık",email:"acelya@example.com",phone:"+91 98765 12001",room:"101",type:"Deluxe",checkIn:"2026-09-22",checkOut:"2026-09-25",status:"Checked in",amount:420,paid:420,method:"Card"},
{ id:1002,guest:"Sony Entertainment",email:"sony@example.com",phone:"+91 98765 12002",room:"204",type:"Deluxe",checkIn:"2026-09-22",checkOut:"2026-09-24",status:"Confirmed",amount:280,paid:140,method:"Card"},
{ id:1003,guest:"Marry TicketCoWorker",email:"marry@example.com",phone:"+91 98765 12003",room:"305",type:"Deluxe",checkIn:"2026-09-23",checkOut:"2026-09-27",status:"Confirmed",amount:560,paid:0,method:"Pending"},
{ id:1004,guest:"Khaled Hussein",email:"khaled@example.com",phone:"+91 98765 12004",room:"402",type:"Deluxe",checkIn:"2026-09-21",checkOut:"2026-09-23",status:"Checked in",amount:260,paid:260,method:"Cash"},
{ id:1005,guest:"Maya Nasreen",email:"maya@example.com",phone:"+91 98765 12005",room:"108",type:"Deluxe",checkIn:"2026-09-24",checkOut:"2026-09-26",status:"Pending",amount:220,paid:0,method:"Pending"}
];

const nav=[["▦","Dashboard"],["▣","Reservations"],["♙","Customers"],["▤","Rooms"],["◈","Payments"],["▥","Reports"],["⚙","Settings"]] as const;

function money(n:number){return `₹${Math.round(n).toLocaleString("en-IN")}`}
function csv(rows:any[],name:string){
 const keys=Object.keys(rows[0]||{});
 const esc=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`;
 const body=[keys.map(esc).join(","),...rows.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n");
 const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href);
}

export default function HotelApp(){
 const [logged,setLogged]=useState(false),[page,setPage]=useState("Dashboard");
 const [reservations,setReservations]=useState<Reservation[]>(seedReservations),[rooms,setRooms]=useState<Room[]>(seedRooms);
 const [query,setQuery]=useState(""),[showNew,setShowNew]=useState(false),[toast,setToast]=useState("");
 const [profile,setProfile]=useState({name:"GrandStay Hotel",phone:"+91 120 456 7800",currency:"INR"});
 const [role,setRole]=useState<"admin"|"user"|null>(null);
 const [userEmail,setUserEmail]=useState("");
 const [userName,setUserName]=useState("");
 useEffect(()=>{
  fetch("/api/auth/me").then(r=>{if(r.ok){setLogged(true);setRole("admin")}}).catch(()=>{});
  if(supabase){supabase.auth.getSession().then(({data})=>{if(data.session){setLogged(true);setRole("user");setUserEmail(data.session.user.email||"");setUserName(data.session.user.user_metadata?.full_name||data.session.user.email?.split("@")[0]||"Guest")}});
   const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(session){setLogged(true);setRole("user");setUserEmail(session.user.email||"");setUserName(session.user.user_metadata?.full_name||session.user.email?.split("@")[0]||"Guest")}});
   return ()=>subscription.unsubscribe();
  }
  try{const r=localStorage.getItem("grandstay_reservations"),rm=localStorage.getItem("grandstay_rooms"),p=localStorage.getItem("grandstay_profile");if(r)setReservations(JSON.parse(r));if(rm)setRooms(JSON.parse(rm));if(p)setProfile(JSON.parse(p));}catch{}
 },[]);
 useEffect(()=>{if(logged){localStorage.setItem("grandstay_reservations",JSON.stringify(reservations));localStorage.setItem("grandstay_rooms",JSON.stringify(rooms));}},[logged,reservations,rooms]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2400)};
 const login=async(email:string,password:string)=>{try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});if(r.ok){setLogged(true);notify("Welcome to GrandStay");return true}}catch{}return false};
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?reservations.filter(r=>`${r.id} ${r.guest} ${r.email} ${r.room} ${r.status}`.toLowerCase().includes(q)):reservations},[reservations,query]);
 if(!logged)return <Login onAdminLogin={login}/>;
 if(role==="user") return <UserPortal email={userEmail} name={userName} onLogout={async()=>{await supabase?.auth.signOut();setLogged(false);setRole(null)}}/>;
 const updateStatus=(id:number,status:Status)=>{setReservations(rs=>rs.map(r=>r.id===id?{...r,status}:r));notify(`Reservation #${id} marked ${status}`)};
 const saveReservation=(r:Reservation)=>{setReservations(rs=>[r,...rs]);setRooms(rs=>rs.map(x=>x.number===r.room?{...x,status:"Reserved",guest:r.guest}:x));setShowNew(false);notify(`Reservation #${r.id} created`)}
 const changeRoom=(num:string,status:RoomStatus)=>{setRooms(rs=>rs.map(r=>r.number===num?{...r,status}:r));notify(`Room ${num} updated`)};
 const pay=(id:number,amount:number,method:string)=>{setReservations(rs=>rs.map(r=>r.id===id?{...r,paid:Math.min(r.amount,r.paid+amount),method}:r));notify(`Payment of ${money(amount)} recorded`)};
 const logout=async()=>{try{await fetch("/api/auth/logout",{method:"POST"})}catch{}localStorage.removeItem("grandstay_logged");setLogged(false);setRole(null)};
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><div className="brandmark">G</div><div>GrandStay<small>HOTEL MANAGEMENT</small></div></div>
   <nav className="nav">{nav.map(([icon,name])=><button key={name} className={page===name?"active":""} onClick={()=>setPage(name)}><span className="nav-icon">{icon}</span>{name}</button>)}</nav>
   <div className="side-bottom">GrandStay PMS · v2.0<br/>All systems operational<br/><br/>© 2026 GrandStay. All rights reserved. · Omkar</div>
  </aside>
  <main className="main"><header className="topbar"><h1>{page}</h1><div className="topright"><span className="muted">Front desk · Online</span><div className="avatar">GS</div><button className="btn" onClick={logout}>Sign out</button></div></header>
   <section className="content">
    {page==="Dashboard"&&<Dashboard reservations={reservations} rooms={rooms} setPage={setPage}/>}
    {page==="Reservations"&&<Reservations rows={filtered} query={query} setQuery={setQuery} onNew={()=>setShowNew(true)} onStatus={updateStatus} onExport={()=>csv(reservations,"grandstay-reservations.csv")}/>}
    {page==="Customers"&&<Customers reservations={reservations}/>}
    {page==="Rooms"&&<Rooms rooms={rooms} changeRoom={changeRoom}/>}
    {page==="Payments"&&<Payments reservations={reservations} onPay={pay} onExport={()=>csv(reservations.map(r=>({reference:`PAY-${r.id}`,guest:r.guest,room:r.room,amount:r.amount,paid:r.paid,balance:r.amount-r.paid,method:r.method} as any)),"grandstay-payments.csv")}/>}
    {page==="Reports"&&<Reports reservations={reservations} rooms={rooms}/>}
    {page==="Settings"&&<Settings profile={profile} setProfile={setProfile} notify={notify}/>}
   </section>
  </main>
  <div className="mobilebar">{nav.slice(0,5).map(([icon,name])=><button key={name} onClick={()=>setPage(name)}>{icon}<br/>{name}</button>)}</div>
  {showNew&&<NewReservation rooms={rooms} reservations={reservations} onClose={()=>setShowNew(false)} onSave={saveReservation}/>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}

function Login({onAdminLogin}:{onAdminLogin:(e:string,p:string)=>Promise<boolean>}){
 const [mode,setMode]=useState<"guest"|"admin">("guest"),[register,setRegister]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[pass,setPass]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
 const submit=async()=>{setError("");setBusy(true);try{if(mode==="admin"){if(!(await onAdminLogin(email,pass)))setError("Invalid admin email or password.");return}if(!supabase){setError("Customer authentication is not configured. Add Supabase variables in Vercel.");return}if(register){if(!name.trim()||pass.length<8){setError("Enter your name and a password with at least 8 characters.");return}const {error}=await supabase.auth.signUp({email,password:pass,options:{data:{full_name:name},emailRedirectTo:typeof window!=="undefined"?window.location.origin:undefined}});if(error)throw error;setSent(true);}else{const {error}=await supabase.auth.signInWithPassword({email,password:pass});if(error)throw error}}catch(e:any){setError(e?.message||"Unable to continue.")}finally{setBusy(false)}};
 const google=async()=>{setError("");if(!supabase){setError("Customer authentication is not configured. Add Supabase variables in Vercel.");return}const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:typeof window!=="undefined"?window.location.origin:undefined}});if(error)setError(error.message)};
 return <div className="login"><div className="login-hero"><span className="hero-pill">✦ GRANDSTAY · LUXURY HOTEL</span><h1>Stay somewhere worth remembering.</h1><p>Discover beautiful rooms, book in minutes, pay securely and keep every reservation in one elegant place.</p><div className="login-showcase"><img src={roomImages[0]} alt="GrandStay deluxe room"/><img src={roomImages[2]} alt="GrandStay suite"/><img src={roomImages[4]} alt="GrandStay bedroom"/></div></div><div className="loginbox-wrap"><div className="loginbox"><div className="brand" style={{color:"#101828",padding:0}}><div className="brandmark">G</div>GrandStay</div><div className="auth-tabs"><button className={mode==="guest"?"active":""} onClick={()=>{setMode("guest");setError("")}}>Guest</button><button className={mode==="admin"?"active":""} onClick={()=>{setMode("admin");setError("")}}>Admin</button></div><h1>{mode==="admin"?"Admin sign in":register?"Create your account":"Welcome back"}</h1><p className="muted">{mode==="admin"?"Private hotel operations workspace.":register?"Create a guest account to book and manage your stays.":"Sign in to book rooms and manage your reservations."}</p>{mode==="guest"&&register&&<input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/>}<input className="input" value={mode==="admin"?email:email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email"/><input className="input" type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Password"/>{error&&<div className="notice-error">{error}</div>}{sent&&<div className="notice">Check your email to confirm your account, then sign in.</div>}<button className="btn primary" disabled={busy} onClick={submit}>{busy?"Please wait…":mode==="admin"?"Sign in as admin":register?"Create account":"Sign in"}</button>{mode==="guest"&&<><div className="or"><span>or</span></div><button className="btn google" onClick={google}>Continue with Google</button><button className="link-btn auth-switch" onClick={()=>{setRegister(!register);setError("")}}>{register?"Already have an account? Sign in":"New to GrandStay? Create an account"}</button></>}{mode==="admin"&&<div className="notice"><b>Admin access</b><br/>Use the separate credentials configured in Vercel environment variables.</div>}</div></div></div>
}

function UserPortal({email,name,onLogout}:{email:string;name:string;onLogout:()=>Promise<void>}){
 const [rooms,setRooms]=useState<Room[]>(seedRooms),[bookings,setBookings]=useState<any[]>([]),[selected,setSelected]=useState<Room|null>(null),[checkIn,setCheckIn]=useState("2026-10-01"),[checkOut,setCheckOut]=useState("2026-10-03"),[payMethod,setPayMethod]=useState("pay_at_hotel"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{if(!supabase)return;supabase.from("bookings").select("*").order("created_at",{ascending:false}).then(({data})=>setBookings(data||[]));},[]);
 const nights=Math.max(1,Math.ceil((new Date(checkOut).getTime()-new Date(checkIn).getTime())/86400000)), amount=(selected?.rate||0)*nights;
 const loadRazorpay=()=>new Promise<boolean>(resolve=>{if((window as any).Razorpay)return resolve(true);const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)});
 const createBooking=async()=>{setError("");setMessage("");if(!supabase){setError("Booking database is not configured.");return}if(!selected){setError("Choose a room first.");return}if(checkOut<=checkIn){setError("Check-out must be after check-in.");return}setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in again.");const base={user_id:user.id,guest_name:name||user.user_metadata?.full_name||"Guest",guest_email:email,guest_phone:user.phone||"",room_number:selected.number,room_type:selected.type,check_in:checkIn,check_out:checkOut,nights,amount,payment_status:payMethod==="pay_at_hotel"?"pending":"paid",payment_method:payMethod,booking_status:"Confirmed"};
  if(payMethod==="pay_at_hotel"){const {data,error}=await supabase.from("bookings").insert(base).select().single();if(error)throw error;setBookings(b=>[data,...b]);setMessage("Reservation confirmed. Pay at the hotel on arrival.");}
  else{const ok=await loadRazorpay();if(!ok)throw new Error("Unable to load Razorpay checkout.");const order=await fetch("/api/payments/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,receipt:`GS-${Date.now()}`})}).then(r=>r.json());if(!order.id)throw new Error(order.error||"Unable to start payment.");await new Promise<void>((resolve,reject)=>{const rz=new (window as any).Razorpay({key:order.key,amount:order.amount,currency:order.currency,name:"GrandStay",description:`${selected.type} Room ${selected.number}`,order_id:order.id,prefill:{name,email},theme:{color:"#b8842d"},handler:async(resp:any)=>{try{const verified=await fetch("/api/payments/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({order_id:resp.razorpay_order_id,payment_id:resp.razorpay_payment_id,signature:resp.razorpay_signature})}).then(r=>r.json());if(!verified.ok)throw new Error(verified.error);const {data,error}=await supabase.from("bookings").insert({...base,payment_status:"paid",payment_reference:resp.razorpay_payment_id}).select().single();if(error)throw error;setBookings(b=>[data,...b]);setMessage("Payment successful — your reservation is confirmed.");resolve();}catch(e:any){reject(e)}},modal:{ondismiss:()=>reject(new Error("Payment was cancelled."))}});rz.open()});}}
 catch(e:any){setError(e?.message||"Unable to complete booking.")}finally{setBusy(false)}};
 return <div className="guest-page"><header className="guest-nav"><div className="brand" style={{color:"#101828",padding:0}}><div className="brandmark">G</div>GrandStay</div><div className="guest-nav-actions"><span>Hi, {name||email.split("@")[0]}</span><button className="btn" onClick={onLogout}>Sign out</button></div></header><main className="guest-content"><section className="guest-hero"><div><span className="hero-pill">GRANDSTAY · PREMIUM STAYS</span><h1>Find your next beautiful stay.</h1><p>Handpicked rooms, flexible booking and secure payments — all from your guest account.</p></div></section><div className="guest-section-head"><div><div className="eyebrow">Book a room</div><h2 className="page-title">Rooms designed for better stays</h2></div></div><div className="booking-grid">{rooms.filter(r=>r.status!=="Maintenance").map(r=><article className={`guest-room ${selected?.number===r.number?"selected":""}`} key={r.number} onClick={()=>setSelected(r)}><img src={r.image} alt={`${r.type} room ${r.number}`}/><div className="guest-room-body"><div className="room-top"><span className="badge blue">{r.type}</span><span className="price">{money(r.rate)}</span></div><h3>GrandStay Room {r.number}</h3><p>Premium bedding · Wi‑Fi · climate control · breakfast available</p><button className="btn primary">{selected?.number===r.number?"Selected":"Choose room"}</button></div></article>)}</div>{selected&&<section className="card booking-panel"><div><div className="eyebrow">Your stay</div><h2>{selected.type} · Room {selected.number}</h2><p className="muted">{money(selected.rate)} per night · {nights} nights · <b>{money(amount)}</b> total</p></div><div className="form-grid"><div className="field"><label>Check-in</label><input className="input" type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)}/></div><div className="field"><label>Check-out</label><input className="input" type="date" value={checkOut} onChange={e=>setCheckOut(e.target.value)}/></div><div className="field"><label>Payment</label><select className="input" value={payMethod} onChange={e=>setPayMethod(e.target.value)}><option value="pay_at_hotel">Pay at hotel</option><option value="razorpay">Card / UPI / NetBanking</option></select></div><div className="field"><label>Guest</label><input className="input" value={name||email} disabled/></div></div>{error&&<div className="notice-error">{error}</div>}{message&&<div className="notice">{message}</div>}<button className="btn gold book-btn" disabled={busy} onClick={createBooking}>{busy?"Processing…":payMethod==="razorpay"?`Pay ${money(amount)} & confirm`:`Confirm reservation · ${money(amount)}`}</button></section>}
 <section style={{marginTop:28}}><div className="eyebrow">My stays</div><h2 className="page-title">Your reservations</h2><div className="card tablewrap"><table className="table"><thead><tr><th>Room</th><th>Dates</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><b>{b.room_type}</b><br/><span className="kpi-note">Room {b.room_number}</span></td><td>{b.check_in} → {b.check_out}</td><td>{money(Number(b.amount))}</td><td>{b.payment_status}</td><td><Badge s={b.booking_status}/></td></tr>)}{!bookings.length&&<tr><td colSpan={5} className="empty">Your confirmed stays will appear here.</td></tr>}</tbody></table></div></section></main><footer className="guest-footer">© 2026 GrandStay. All rights reserved. · Omkar</footer></div>
}

function Dashboard({reservations,rooms,setPage}:{reservations:Reservation[];rooms:Room[];setPage:(p:string)=>void}){
 const revenue=reservations.reduce((s,r)=>s+r.paid,0),occ=rooms.filter(r=>r.status==="Occupied").length;
 return <><div className="hero-grid"><div className="hotel-hero"><span className="hero-pill">GRANDSTAY · NEW DELHI REGION</span><h2>Welcome to GrandStay</h2><div>Luxury stays. Smarter operations. One calm dashboard.</div></div><div className="mini-card"><div className="section-head"><h2>Property snapshot</h2><Badge s="System online"/></div><div style={{display:"grid",gap:13}}><Progress label="Occupancy" value={occ} total={rooms.length}/><Progress label="Clean & ready" value={rooms.filter(r=>r.status==="Clean").length} total={rooms.length}/><Progress label="Reservations paid" value={reservations.filter(r=>r.paid>=r.amount).length} total={reservations.length}/></div></div></div>
 <div className="eyebrow">Today · 23 September 2026</div><h2 className="page-title">Good evening, Admin</h2><p className="muted">Here is what is happening across your property today.</p>
 <div className="grid4"><Stat label="Occupancy" value={`${Math.round(occ/rooms.length*100)}%`} trend="+6.2% vs last week" icon="◉"/><Stat label="Arrivals" value={String(reservations.filter(r=>r.checkIn==="2026-09-23"&&r.status!=="Cancelled").length+7)} trend="Today's check-ins" icon="→"/><Stat label="Departures" value="9" trend="2 rooms pending" icon="←"/><Stat label="Collected" value={money(revenue)} trend="Across current folios" icon="₹"/></div>
 <div className="two"><div className="card"><div className="section-head"><h2>Recent reservations</h2><button className="link-btn" onClick={()=>setPage("Reservations")}>View all →</button></div><div className="tablewrap"><table className="table"><thead><tr><th>Guest</th><th>Room</th><th>Stay</th><th>Status</th><th>Paid</th></tr></thead><tbody>{reservations.slice(0,5).map(r=><tr key={r.id}><td><b>{r.guest}</b><br/><span className="kpi-note">#{r.id}</span></td><td>{r.room}</td><td>{r.checkIn} → {r.checkOut}</td><td><Badge s={r.status}/></td><td>{money(r.paid)}</td></tr>)}</tbody></table></div></div>
 <div className="card"><div className="section-head"><h2>Room status</h2><button className="link-btn" onClick={()=>setPage("Rooms")}>Manage →</button></div><div style={{display:"grid",gap:15}}><Progress label="Occupied" value={rooms.filter(r=>r.status==="Occupied").length} total={rooms.length}/><Progress label="Clean & ready" value={rooms.filter(r=>r.status==="Clean").length} total={rooms.length}/><Progress label="Reserved" value={rooms.filter(r=>r.status==="Reserved").length} total={rooms.length}/><Progress label="Maintenance" value={rooms.filter(r=>r.status==="Maintenance").length} total={rooms.length}/></div></div></div>
 <div className="card" style={{marginTop:18}}><div className="section-head"><h2>Stay inspiration</h2><span className="muted">Rooms guests love</span></div><div className="room-gallery">{roomImages.slice(0,3).map((x,i)=><img key={x} src={x} alt={["Deluxe room","Suite interior","Grand bedroom"][i]}/>)}</div></div></>
}
function Stat({label,value,trend,icon}:{label:string;value:string;trend:string;icon:string}){return <div className="card stat"><div><div className="label">{label}</div><div className="value">{value}</div><div className="trend">{trend}</div></div><div className="icon">{icon}</div></div>}
function Progress({label,value,total}:{label:string;value:number;total:number}){return <div><div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:7}}><span>{label}</span><b>{value}</b></div><div className="bar"><span style={{width:`${total?Math.min(100,value/total*100):0}%`}}/></div></div>}
function Badge({s}:{s:string}){const c=s==="Checked in"||s==="Paid"||s==="Clean"||s==="System online"?"green":s==="Confirmed"||s==="Reserved"||s==="Occupied"?"blue":s==="Pending"||s==="Dirty"?"amber":s==="Cancelled"||s==="Maintenance"?"red":"gray";return <span className={`badge ${c}`}>{s}</span>}

function Reservations({rows,query,setQuery,onNew,onStatus,onExport}:{rows:Reservation[];query:string;setQuery:(v:string)=>void;onNew:()=>void;onStatus:(id:number,s:Status)=>void;onExport:()=>void}){
 return <><div className="section-head"><div><div className="eyebrow">Front desk</div><h2 className="page-title">Reservations</h2><div className="muted">Create, search, check guests in/out and manage every stay.</div></div><div className="actions"><button className="btn" onClick={onExport}>↓ Export CSV</button><button className="btn primary" onClick={onNew}>＋ New reservation</button></div></div>
 <div className="card"><div className="filters"><input className="input grow" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search guest, room, reference, email..."/><button className="btn" onClick={()=>setQuery("Confirmed")}>Confirmed</button><button className="btn" onClick={()=>setQuery("")}>Clear</button></div><div className="tablewrap"><table className="table"><thead><tr><th>Reference</th><th>Guest</th><th>Room</th><th>Dates</th><th>Status</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>#{r.id}</td><td><b>{r.guest}</b><br/><span className="kpi-note">{r.email}</span></td><td>{r.room}<br/><span className="kpi-note">{r.type}</span></td><td>{r.checkIn}<br/>{r.checkOut}</td><td><Badge s={r.status}/></td><td>{money(r.amount)}<br/><span className="kpi-note">paid {money(r.paid)}</span></td><td><select className="input" value={r.status} onChange={e=>onStatus(r.id,e.target.value as Status)}><option>Pending</option><option>Confirmed</option><option>Checked in</option><option>Checked out</option><option>Cancelled</option></select></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No reservations match your search.</div>}</div></div></>
}

function Customers({reservations}:{reservations:Reservation[]}){
 return <><div className="eyebrow">Guest directory</div><h2 className="page-title">Customers</h2><p className="muted">Guest profiles automatically built from reservations.</p><div className="card"><table className="table"><thead><tr><th>Guest</th><th>Contact</th><th>Reservation</th><th>Room</th><th>Stay</th><th>Spend</th></tr></thead><tbody>{reservations.map(r=><tr key={r.id}><td><b>{r.guest}</b></td><td>{r.phone}<br/>{r.email}</td><td>#{r.id}</td><td>{r.room} · {r.type}</td><td>{r.checkIn} → {r.checkOut}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div></>
}

function Rooms({rooms,changeRoom}:{rooms:Room[];changeRoom:(n:string,s:RoomStatus)=>void}){
 return <><div className="eyebrow">Property operations</div><h2 className="page-title">Rooms & inventory</h2><p className="muted">Live housekeeping and availability board. Update status from the card.</p><div className="rooms" style={{marginTop:20}}>{rooms.map(r=><div className="room card" key={r.number}><img className="room-img" src={r.image} alt={`${r.type} room ${r.number}`}/><div className="room-body"><div style={{display:"flex",justifyContent:"space-between",gap:8}}><span className="roomnum">Room {r.number}</span><Badge s={r.status}/></div><div className="roommeta">{r.type} · {money(r.rate)}/night {r.guest&&<>· {r.guest}</>}</div><div className="room-controls"><select className="input" value={r.status} onChange={e=>changeRoom(r.number,e.target.value as RoomStatus)}><option>Clean</option><option>Dirty</option><option>Occupied</option><option>Reserved</option><option>Maintenance</option></select></div></div></div>)}</div></>
}

function Payments({reservations,onPay,onExport}:{reservations:Reservation[];onPay:(id:number,a:number,m:string)=>void;onExport:()=>void}){
 const total=reservations.reduce((s,r)=>s+r.paid,0),out=reservations.reduce((s,r)=>s+r.amount-r.paid,0);
 return <><div className="section-head"><div><div className="eyebrow">Cash desk</div><h2 className="page-title">Payments & folios</h2><p className="muted">Record payments, monitor balances and export your ledger.</p></div><button className="btn" onClick={onExport}>↓ Export payments CSV</button></div><div className="grid4"><Stat label="Collected" value={money(total)} trend="Current folios" icon="✓"/><Stat label="Outstanding" value={money(out)} trend="Amount to collect" icon="◌"/><Stat label="Paid folios" value={String(reservations.filter(r=>r.paid>=r.amount).length)} trend="Fully settled" icon="▣"/><Stat label="Transactions" value={String(reservations.length)} trend="Active ledger" icon="₹"/></div><div className="card"><table className="table"><thead><tr><th>Guest</th><th>Reference</th><th>Method</th><th>Total</th><th>Paid</th><th>Balance</th><th>Action</th></tr></thead><tbody>{reservations.map(r=><tr key={r.id}><td>{r.guest}</td><td>PAY-{r.id}</td><td>{r.method}</td><td>{money(r.amount)}</td><td>{money(r.paid)}</td><td>{money(r.amount-r.paid)}</td><td>{r.paid<r.amount?<button className="btn primary" onClick={()=>onPay(r.id,r.amount-r.paid,"Card")}>Collect balance</button>:<Badge s="Paid"/>}</td></tr>)}</tbody></table></div></>
}

function Reports({reservations,rooms}:{reservations:Reservation[];rooms:Room[]}){
 const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], revenue=reservations.reduce((s,r)=>s+r.paid,0);
 return <><div className="section-head"><div><div className="eyebrow">Analytics</div><h2 className="page-title">Reports</h2><p className="muted">Operational snapshot for management.</p></div><button className="btn primary" onClick={()=>csv(reservations.map(r=>({reference:r.id,guest:r.guest,room:r.room,checkIn:r.checkIn,checkOut:r.checkOut,status:r.status,amount:r.amount,paid:r.paid,balance:r.amount-r.paid} as any)),"grandstay-report.csv")}>↓ Export report</button></div>
 <div className="two"><div className="card"><div className="section-head"><h2>Weekly occupancy</h2><span className="muted">Illustrative trend</span></div>{days.map((d,i)=><div key={d} style={{display:"grid",gridTemplateColumns:"35px 1fr 40px",gap:10,alignItems:"center",margin:"14px 0",fontSize:12}}><span>{d}</span><div className="bar"><span style={{width:`${48+i*6}%`}}/></div><b>{48+i*6}%</b></div>)}</div><div className="card"><div className="section-head"><h2>Property mix</h2></div>{[["Occupied",rooms.filter(r=>r.status==="Occupied").length],["Clean",rooms.filter(r=>r.status==="Clean").length],["Reserved",rooms.filter(r=>r.status==="Reserved").length],["Maintenance",rooms.filter(r=>r.status==="Maintenance").length]].map(([n,v])=><Progress key={String(n)} label={String(n)} value={Number(v)} total={rooms.length}/>)}</div></div>
 <div className="hotel-list" style={{marginTop:18}}>{hotelImages.map((x,i)=><div className="hotel-card card" key={x}><img src={x} alt="GrandStay property"/><div className="body"><div className="stars">★★★★★</div><b>{["GrandStay Palace","GrandStay City View","GrandStay Retreat"][i]}</b><p className="kpi-note">Luxury hospitality · curated rooms · 24/7 front desk</p><span className="price">{money([4500,3800,6200][i])}</span> / night</div></div>)}</div><div className="card" style={{marginTop:18}}><b>Collected revenue</b><div style={{fontSize:32,fontWeight:850,marginTop:8}}>{money(revenue)}</div><div className="kpi-note">Based on recorded payments in this browser workspace.</div></div></>
}

function Settings({profile,setProfile,notify}:{profile:{name:string;phone:string;currency:string};setProfile:(p:any)=>void;notify:(m:string)=>void}){
 const [p,setP]=useState(profile);return <><div className="eyebrow">Administration</div><h2 className="page-title">Settings</h2><p className="muted">Property profile and workspace preferences.</p><div className="two" style={{marginTop:20}}><div className="card"><h2 style={{fontSize:16}}>Hotel profile</h2><div className="field"><label>Hotel name</label><input className="input" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></div><div className="field" style={{marginTop:13}}><label>Phone</label><input className="input" value={p.phone} onChange={e=>setP({...p,phone:e.target.value})}/></div><div className="field" style={{marginTop:13}}><label>Currency</label><select className="input" value={p.currency} onChange={e=>setP({...p,currency:e.target.value})}><option>INR</option><option>USD</option><option>EUR</option></select></div><button className="btn primary" style={{marginTop:16}} onClick={()=>{setProfile(p);localStorage.setItem("grandstay_profile",JSON.stringify(p));notify("Settings saved")}}>Save changes</button></div><div className="card"><h2 style={{fontSize:16}}>Workspace</h2><p className="muted">Timezone: Asia/Kolkata</p><p className="muted">Currency: {profile.currency}</p><p className="muted">Property capacity: {16} rooms in this starter dataset</p><Badge s="System online"/><div className="notice" style={{marginTop:16}}>For production, connect Supabase/Firebase or your own API for real multi-user authentication, database persistence and payment processing.</div></div></div></>
}

function NewReservation({rooms,reservations,onClose,onSave}:{rooms:Room[];reservations:Reservation[];onClose:()=>void;onSave:(r:Reservation)=>void}){
 const today="2026-09-23";const [guest,setGuest]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[room,setRoom]=useState(rooms.find(r=>r.status==="Clean")?.number||rooms[0].number),[checkIn,setCheckIn]=useState(today),[checkOut,setCheckOut]=useState("2026-09-25"),[amount,setAmount]=useState(280),[error,setError]=useState("");
 const selected=rooms.find(r=>r.number===room);
 return <div className="modal-backdrop"><div className="modal"><div className="section-head"><div><div className="eyebrow">Front desk</div><h2 style={{margin:0}}>New reservation</h2></div><button className="btn" onClick={onClose}>×</button></div><div className="form-grid"><div className="field"><label>Guest name *</label><input className="input" value={guest} onChange={e=>setGuest(e.target.value)} placeholder="Full name"/></div><div className="field"><label>Email</label><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="guest@email.com"/></div><div className="field"><label>Phone</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91..."/></div><div className="field"><label>Room *</label><select className="input" value={room} onChange={e=>{setRoom(e.target.value);const x=rooms.find(r=>r.number===e.target.value);if(x)setAmount(x.rate*2)}}>{rooms.filter(r=>r.status==="Clean"||r.number===room).map(r=><option key={r.number} value={r.number}>{r.number} · {r.type} · {money(r.rate)}</option>)}</select></div><div className="field"><label>Check-in</label><input className="input" type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)}/></div><div className="field"><label>Check-out</label><input className="input" type="date" value={checkOut} onChange={e=>setCheckOut(e.target.value)}/></div><div className="field"><label>Total amount</label><input className="input" type="number" min="0" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></div><div className="field"><label>Payment method</label><select className="input" id="method"><option>Pending</option><option>Card</option><option>Cash</option><option>UPI</option></select></div></div>{error&&<div className="notice-error">{error}</div>}<div className="actions" style={{justifyContent:"flex-end",marginTop:20}}><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" onClick={()=>{if(!guest.trim()){setError("Guest name is required.");return}if(checkOut<=checkIn){setError("Check-out must be after check-in.");return}if(reservations.some(r=>r.room===room&&r.status!=="Cancelled"&&checkIn<r.checkOut&&checkOut>r.checkIn)){setError("That room overlaps an existing reservation.");return}const method=(document.getElementById("method") as HTMLSelectElement)?.value||"Pending";onSave({id:Math.floor(1000+Math.random()*9000),guest:guest.trim(),email:email||"—",phone:phone||"—",room,type:selected?.type||"Standard",checkIn,checkOut,status:"Confirmed",amount:Number(amount),paid:0,method})}}>Create reservation</button></div></div></div>
}
